use Mix.Config

config :night_game, :map, {
  {{:obstacle, :wall}, {:obstacle, :wall}, {:obstacle, :wall}, {:obstacle, :wall},
   {:obstacle, :wall}, {:obstacle, :wall}, {:obstacle, :wall}, {:obstacle, :wall},
   {:obstacle, :wall}, {:obstacle, :wall}, {:obstacle, :wall}, {:obstacle, :wall},
   {:obstacle, :wall}, {:obstacle, :wall}, {:obstacle, :wall}, {:obstacle, :wall},
   {:obstacle, :wall}, {:obstacle, :wall}, {:obstacle, :wall}, {:obstacle, :wall},
   {:obstacle, :wall}, {:obstacle, :wall}, {:obstacle, :wall}, {:obstacle, :wall},
   {:obstacle, :wall}, {:obstacle, :wall}, {:obstacle, :wall}, {:obstacle, :wall},
   {:obstacle, :wall}, {:obstacle, :wall}},
  {{:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:obstacle, :wall}},
  {{:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:obstacle, :wall}},
  {{:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:obstacle, :wall}},
  {{:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall},
   {:obstacle, :wall}},
  {{:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall},
   {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:obstacle, :wall}},
  {{:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:obstacle, :wall}},
  {{:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:obstacle, :wall}},
  {{:obstacle, :wall}, {:obstacle, :wall}, {:obstacle, :wall}, {:obstacle, :wall},
   {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:obstacle, :wall}},
  {{:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:obstacle, :wall}},
  {{:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:obstacle, :wall}},
  {{:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall}, {:obstacle, :wall},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:obstacle, :wall}, {:obstacle, :wall}, {:obstacle, :wall},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall}},
  {{:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:obstacle, :wall}},
  {{:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:obstacle, :wall}},
  {{:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:obstacle, :wall}},
  {{:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:obstacle, :wall}},
  {{:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:obstacle, :wall}, {:obstacle, :wall}, {:obstacle, :wall}, {:obstacle, :wall},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:obstacle, :wall}},
  {{:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall}, {:obstacle, :wall},
   {:obstacle, :wall}, {:obstacle, :wall}, {:obstacle, :wall}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:obstacle, :wall}},
  {{:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:obstacle, :wall}},
  {{:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall}, {:obstacle, :wall},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:obstacle, :wall}},
  {{:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:obstacle, :wall}},
  {{:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:obstacle, :wall}},
  {{:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:obstacle, :wall}},
  {{:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:obstacle, :wall}},
  {{:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:obstacle, :wall}},
  {{:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:obstacle, :wall}},
  {{:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:obstacle, :wall}},
  {{:obstacle, :wall}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:obstacle, :wall}, {:ground, :grass}, {:ground, :grass},
   {:ground, :grass}, {:ground, :grass}, {:ground, :grass}, {:ground, :grass},
   {:obstacle, :wall}},
  {{:obstacle, :wall}, {:obstacle, :wall}, {:obstacle, :wall}, {:obstacle, :wall},
   {:obstacle, :wall}, {:obstacle, :wall}, {:obstacle, :wall}, {:obstacle, :wall},
   {:obstacle, :wall}, {:obstacle, :wall}, {:obstacle, :wall}, {:obstacle, :wall},
   {:obstacle, :wall}, {:obstacle, :wall}, {:obstacle, :wall}, {:obstacle, :wall},
   {:obstacle, :wall}, {:obstacle, :wall}, {:obstacle, :wall}, {:obstacle, :wall},
   {:obstacle, :wall}, {:obstacle, :wall}, {:obstacle, :wall}, {:obstacle, :wall},
   {:obstacle, :wall}, {:obstacle, :wall}, {:obstacle, :wall}, {:obstacle, :wall},
   {:obstacle, :wall}, {:obstacle, :wall}}
}
