name: Tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1

    env:
      MIX_ENV: test

    steps:
    - uses: actions/checkout@v1
    - name: Cache Deps
      id: cache-deps
      uses: actions/cache@v1
      with:
        path: deps
        key: ${{ runner.os }}-deps
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Compile
      run: |
        mix deps.compile
        mix compile --warnings-as-errors
    - name: Check Formatting
      run: mix format --check-formatted
    - name: Run Tests
      run:  mix test

